baseURL: "https://sterbemorgen.github.io/"
languageCode: "en-us"
title: "sterbe morgen"
theme: "PaperMod"

params:
  backTopIcon: "/icons/neuroplasticity.png"
  ShowReadingTime: true
  hasCJKLanguage: true
  enableInlineShortcodes: true
  enableEmoji: true
  enableRobotsTXT: true
  buildDrafts: false
  buildFuture: false
  buildExpired: false
  enableEmoji: true
  pygmentsUseClasses: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  giscus:
    repo: "sterbemorgen/sterbemorgen.github.io"
    repo_id: "R_kgDONvALpQ"
    category: "Announcements"
    category_id: "DIC_kwDONvALpc4CmT8P"
    mapping: "pathname"
    strict: false
    reactions_enabled: true
    emit_metadata: false
    input_position: "bottom"
    theme: "preferred_color_scheme"
    lang: "en"
    crossorigin: "anonymous"
    async: true

  profileMode:
    enabled: true
    title: "Khonzy"
    subtitle: "Lebe trotz der Absurdität des Lebens, um es in seiner ganzen Fülle zu erfahren."
    imageUrl: "images/otter.gif"
    imageTitle: "<title of image as alt>"
    imageWidth: 120
    imageHeight: 120
   
    
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/siauyuih"
    - name: "YouTube"
      url: "https://www.youtube.com/@sterbemorgen"
    - name: "email"
      url: "Mailto: sterbemorgen@proton.me"

  assets:
    favicon: "otter.png"
    favicon16x16: "otter.png"
    favicon32x32: "otter.png"
    apple_touch_icon: "otter.png"
    safari_pinned_tab: "otter.png"
    disableFingerprinting: true

menu:
  main:
    - identifier: about
      name: About
      url: "/about"
    - identifier: archives
      name: Archives
      url: "/archives"
    - identifier: search
      name: Search
      url: "/search"
  left-sidebar:
    - identifier: perusal
      name: Perusal
      url: "/perusal"
    - identifier: appreciation
      name: Appreciation
      url: "/appreciation"
    - identifier: introspective
      name: Introspective
      url: "/introspective"
    - identifier: existence
      name: Existence
      url: "/existence"

defaultTheme: auto
preferred_color_scheme: auto
disableThemeToggle: false
DateFormat: "2006-01-02"
ShowShareButtons: true
ShowReadingTime: true
displayFullLangName: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
hideFooter: false
ShowWordCounts: true
VisitCount: true

ShowLastMod: true
ShowToc: true
TocOpen: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: darcula
